src/cl/mker/inv/web/reporte/ReporteResumenVentaBean.java
package cl.mker.inv.web.reporte;

import java.io.ByteArrayInputStream;
import java.util.Date;
import java.util.List;

import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.inject.Inject;

import org.primefaces.model.DefaultStreamedContent;
import org.primefaces.model.StreamedContent;

import cl.mker.inv.modelo.documento.ResumenVenta;
import cl.mker.inv.servicio.ServiceException;
import cl.mker.inv.servicio.documento.ReporteResumenVentaService;
import cl.mker.inv.servicio.documento.ResumenVentaService;

@ManagedBean
@ViewScoped
public class ReporteResumenVentaBean {

	private List<ResumenVenta> resumenVentas;
	
	@Inject
	private ResumenVentaService resumenVentaService;
	
	@Inject
	private ReporteResumenVentaService reporteResumenVentaService;
	
	private Date fechaInicio;
	private Date fechaFin;

	@PostConstruct
	private void init(){
		fechaInicio = new Date();
		fechaFin = new Date();
		
		try {
			resumenVentaService.listaResumenVentas(fechaInicio, fechaFin);
		} catch (ServiceException e){
			e.printStackTrace();
		}
	}
	
	public Date getFechaInicio() {return fechaInicio; }
	public void setFechaInicio(Date fechaInicio) { this.fechaInicio = fechaInicio; }
	public Date getFechaFin() {	return fechaFin; }
	public void setFechaFin(Date fechaFin) { this.fechaFin = fechaFin; }
	public List<ResumenVenta> getResumenVentas() { return resumenVentas; }
	public void setResumenVentas(List<ResumenVenta> resumenVentas) { this.resumenVentas = resumenVentas; }
	
	public void actualizaFecha(){
		try {
			resumenVentas = resumenVentaService.listaResumenVentas(fechaInicio, fechaFin);
		} catch (ServiceException e){
			e.printStackTrace();
		}
	}
	
	public StreamedContent getContent() {
		try {
			return new DefaultStreamedContent(new ByteArrayInputStream(reporteResumenVentaService.listaResumenFacturas(resumenVentas).toByteArray()), "application/pdf", "resumen ventas.pdf");  
		} catch (Exception e) {
			e.printStackTrace();
		}
		
		return null;
	}
}

WebContent/views/app/ventas/listaAbonos.xhtml
<!DOCTYPE html>
<h:html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">

<ui:composition template="/resources/templates/container.xhtml">
	<ui:define name="pageTitle">Administracion de Pagos</ui:define>
	<ui:define name="pageDescription">Lista de Pagos</ui:define>
	<ui:define name="pageLinks">
		<ul class="page-breadcrumb">
			<li>
				<i class="fa fa-home"></i> 
				<h:link value="Inicio" outcome="/views/app/index.html"/>
				<i class="fa fa-angle-right"></i>
			</li>
			<li>
				<h:link value="Lista de Pagos"/>
			</li>
		</ul>
	</ui:define>
	<ui:define name="pageContent">
		<!-- FORM 0 -->
		<h:form id="form0" prependId="false">
			<p:growl id="growl" showDetail="true"/>
			<div class="row">
				<div class="col-md-12">
					<div class="portlet box grey-cascade">
						<div class="portlet-title">
							<div class="caption">
								<i class="fa fa-globe"></i>Lista de pagos
							</div>
						</div>
						<div class="portlet-body">
							<div class="table-toolbar">
								<div class="row">
									<div class="col-md-6">
									</div>
									<div class="col-md-6">
										<div class="btn-group pull-right">
											<button class="btn dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
												Exportar a <i class="fa fa-angle-down"></i>
											</button>
											<ul class="dropdown-menu pull-right">
												<li>
													<h:commandLink value="Excel">
	        											<p:dataExporter type="xls" target="tablaFacturas" fileName="facturas" pageOnly="true" />
	    											</h:commandLink>
												</li>
												<li>
													<h:commandLink value="Pdf">
	        											<p:dataExporter type="pdf" target="tablaFacturas" fileName="facturas" pageOnly="true" />
	    											</h:commandLink>
												</li>
											</ul>
										</div>
									</div>
								</div>
							</div>
							<div id="sample_1_wrapper" class="dataTables_wrapper no-footer">
								<div class="row">
									<div class="col-md-6 col-sm-12">
										<div id="sample_1_filter" class="dataTables_filter">
										</div>
									</div>
								</div>
							</div>
							<div>
								<!-- BEGIN TABLA -->
								<p:dataTable 
									id="tablaFacturas" 
									widgetVar="tablaFacturasWidgetVar"
									value="#{abonoBean.resumenFacturas}"
									var="resumenFactura" 
									paginatorTemplate="{CurrentPageReport} {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink}"
									paginatorPosition="bottom"
									paginator="true" 
									rows="5" 
									style="margin-bottom:20px">
								 
									<p:column>
									    <f:facet name="header">
									        <h:outputText value="Id"/>
									    </f:facet>
									    <h:outputText value="#{resumenFactura.idFactura}" />
									</p:column>
									<p:column>
									    <f:facet name="header">
									        <h:outputText value="Numero factura"/>
									    </f:facet>
									    <h:outputText value="#{resumenFactura.numeroFactura}" />
									</p:column>
									<p:column>
									    <f:facet name="header">
									        <h:outputText value="Fecha"/>
									    </f:facet>
									    <h:outputText value="#{resumenFactura.fecha}" />
									</p:column>
									<p:column>
									    <f:facet name="header">
									        <h:outputText value="IVA"/>
									    </f:facet>
									    <h:outputText value="#{resumenFactura.porcentaje}" />
									</p:column>
									<p:column>
									    <f:facet name="header">
									        <h:outputText value="Total bruto"/>
									    </f:facet>
									    <h:outputText value="#{resumenFactura.totalBruto}" />
									</p:column>
									<p:column>
									    <f:facet name="header">
									        <h:outputText value="Total neto"/>
									    </f:facet>
									    <h:outputText value="#{resumenFactura.totalNeto}" />
									</p:column>
									<!-- Selecciona Factura -->
									<p:column exportable="false" style="width:50px">
           								<p:commandButton icon="ui-icon-search" title="Modifica orden" oncomplete="PF('dialog').show()" update=":form0">
           									<f:setPropertyActionListener value="#{resumenFactura}" target="#{abonoBean.resumenFacturaSeleccionada}" />
           								</p:commandButton>
       								</p:column>
								</p:dataTable>
								<!-- END TABLA -->
							</div>
						</div>
					</div>
				</div>
			</div>
		</h:form>
		<!-- FIN FORM 0 -->
		<!-- FORM 1 -->
		<h:form id="form1">
			<p:growl id="growl" showDetail="true"/>
			<p:dialog 
					id="idDialog"
					showHeader="false"
					widgetVar="dialog" 
					showEffect="fade"  
					draggable="false" 
					modal="true" 
					closable="false" 
					dynamic="true" 
					position="center"
					resizable="false"
					width="80%"
					height="800px">
					
				<div class="row">
					<div class="col-md-12">
						<div class="portlet box grey-cascade">
							<div class="portlet-title">
								<div class="caption">
									<i class="fa fa-globe"></i>Lista de Materiales y Devoluciones
								</div>
							</div>
							<div class="portlet-body">
								<div class="table-toolbar">
									<div class="row">
										<div class="col-md-6">
											<div class="btn-group">
												<p:commandButton value="Nuevo Abono +" id="sample_editable_1_new" class="btn green" actionListener="#{abonoBean.asignaNuevoAbono()}" oncomplete="PF('dialog1').show()" />
											</div>
										</div>	
										<div class="col-md-6">
											<div class="btn-group pull-right">
												<button class="btn dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
													Exportar a <i class="fa fa-angle-down"></i>
												</button>
												<ul class="dropdown-menu pull-right">
													<li>
														<h:commandLink value="Excel">
		        											<p:dataExporter type="xls" target="tablaAbonos" fileName="abonos" pageOnly="true" />
		    											</h:commandLink>
													</li>
													<li>
														<h:commandLink value="Pdf">
		        											<p:dataExporter type="pdf" target="tablaAbonos" fileName="abonos" pageOnly="true" />
		    											</h:commandLink>
													</li>
												</ul>
											</div>
										</div>
									</div>
								</div>
								<div>
									<p:dataTable 
											id="tablaAbonos"
											value="#{abonoBean.abonos}" 
											var="abono"
											paginator="true"
											rows="10"
											rowsPerPageTemplate="10,20,30"
											style="margin-bottom:20px" 
											>
										
										<p:column headerText="Id">
											<h:outputText value="#{abono.idAbono}"/>
									    </p:column>
	
									    <p:column headerText="Fecha">
											<h:outputText value="#{abono.fecha}" />
									    </p:column>
									    
									    <p:column headerText="Monto">
											<h:outputText value="#{abono.monto}" />
									    </p:column>
									    
									    <p:column exportable="false" style="width:70px" headerText="Elimina">
			           						<p:commandButton icon="ui-icon-trash" title="Elimina abono" actionListener="#{abonoBean.eliminaAbono(abono)}" update=":form1:tablaAbonos">
			           							<p:confirm header="Confirma" message="¿ Estás seguro ?" icon="ui-icon-alert" />
			           						</p:commandButton>
			       						</p:column>
									</p:dataTable>
									
									<p:confirmDialog global="true" showEffect="fade" hideEffect="fade" closable="false" >
								        <p:commandButton value="Elimina" type="button" styleClass="ui-confirmdialog-yes" icon="ui-icon-check" />
								        <p:commandButton value="Cancela" type="button" styleClass="ui-confirmdialog-no" icon="ui-icon-close" />
								    </p:confirmDialog>
									
								</div>	
								<div class="form-actions">
									<p:commandButton value="Cerrar" id="sample_editable_1_edit" class="btn default" update="idDialog" oncomplete="PF('dialog').hide()"  />
								</div>
							</div>
						</div>
					</div>
				</div>				
			</p:dialog>
		</h:form>
		<!-- END FORM 1 -->
		<!-- FORM 2 -->
		<h:form id="form2">
			<p:growl id="growl" showDetail="true" autoUpdate="true"/>
			<p:dialog 
					id="idDialog1"
					showHeader="false"
					draggable="false" 
					widgetVar="dialog1" 
					showEffect="fade"  
					modal="true" 
					closable="false" 
					dynamic="true" 
					position="center"
					resizable="false"
					width="50%"	>
				
				<div class="row">
					<div class="col-md-12">
						<!-- BEGIN Portlet PORTLET-->
						<div class="portlet box green">
							<div class="portlet-title">
								<div class="caption">
									<i class="fa fa-gift"></i>Formulario de Abono
								</div>
							</div>
							<div class="portlet-body form portlet-empty">
								<div class="form-body">
									<div class="form-group">
										<label for="monto">Monto</label>
											<p:spinner 
												id="minMax" 
												value="#{abonoBean.abono.monto}" 
												min="0" 
												max="#{abonoBean.montoMaximo()}" />
										<span class="help-block">
										</span>
									</div>
								</div>
								<div class="form-actions">
									<p:commandButton value="Confirme" id="sample_editable_2_new" class="btn green" update=":form1:tablaAbonos" actionListener="#{abonoBean.registraAbono()}" />
									<p:commandButton value="Cancela" id="sample_editable_1_edit" class="btn default" update="idDialog1" oncomplete="PF('dialog1').hide()"  />
								</div>
							</div>
						</div>
						<!-- END Portlet PORTLET-->
					</div>
				</div>
			</p:dialog>
		</h:form>
		<!-- END FORM 2 -->
	</ui:define>
</ui:composition>
</h:html>

WebContent/views/app/ventas/listaFacturas.xhtml
<!DOCTYPE html>
<h:html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui"
	xmlns:pt="http://xmlns.jcp.org/jsf/passthrough">>

<ui:composition template="/resources/templates/container.xhtml">
	<ui:define name="pageTitle">Administracion de Facturas</ui:define>
	<ui:define name="pageDescription">Lista de Facturas</ui:define>
	<ui:define name="pageLinks">
		<ul class="page-breadcrumb">
			<li>
				<i class="fa fa-home"></i> 
				<h:link value="Inicio" outcome="/views/app/index.html"/>
				<i class="fa fa-angle-right"></i>
			</li>
			<li>
				<h:link value="Lista de Facturas"/>
			</li>
		</ul>
	</ui:define>
	<ui:define name="pageContent">
		<h:form id="form0" prependId="false">
        <p:growl id="messages" showDetail="true" autoUpdate="true" closable="true" showSummary="false"/>
			<div class="row">
				<div class="col-md-12">
					<div class="portlet box grey-cascade">
						<div class="portlet-title">
							<div class="caption">
								<i class="fa fa-globe"></i>Lista de facturas
							</div>
						</div>
						<div class="portlet-body">
							<div class="table-toolbar">
								<div class="row">
									<div class="col-md-6">
										<div class="btn-group">
											<p:commandButton value="Nueva Factura +" id="sample_editable_1_new" class="btn green" update=":form1 :formAuto" actionListener="#{facturaBean.asignaNuevaFactura()}" oncomplete="PF('dialog').show()" />
										</div> 
									</div>
									<div class="col-md-6">
										<div class="btn-group pull-right">
											<button class="btn dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
												Exportar a <i class="fa fa-angle-down"></i>
											</button>
											<ul class="dropdown-menu pull-right">
												<li>
													<h:commandLink value="Excel">
	        											<p:dataExporter type="xls" target="tablaFacturas" fileName="prodcutos" pageOnly="true" />
	    											</h:commandLink>
												</li>
												<li>
													<h:commandLink value="Pdf">
	        											<p:dataExporter type="pdf" target="tablaFacturas" fileName="productos" pageOnly="true" />
	    											</h:commandLink>
												</li>
											</ul>
										</div>
									</div>
								</div>
							</div>
							<div id="sample_1_wrapper" class="dataTables_wrapper no-footer">
								<div class="row">
									<div class="col-md-6 col-sm-12">
										<div id="sample_1_filter" class="dataTables_filter">
										</div>
									</div>
								</div>
							</div>
							<div>
							
								<!-- BEGIN TABLA -->
								<p:dataTable 
										id="tablaFacturas"
										value="#{facturaBean.facturas}" 
										var="factura"
										paginator="true"
										rows="10"
										rowsPerPageTemplate="10,20,30"
										style="margin-bottom:20px"
										update="@form"
										paginatorPosition="bottom"
										filteredValue="#{facturaBean.facturasFiltradas}"
										emptyMessage="No se encontraron registros">
									
									<f:facet name="header">
										<div align="left">        
											<h:outputText value="Filtrado por :" />
										</div>
									</f:facet>
									
									<p:column headerText="Id" filterBy="#{factura.idFactura}" filterMatchMode="contains">
										<h:outputText value="#{factura.idFactura}"/>
								    </p:column>
								    
								    <p:column headerText="Numero Factura" filterBy="#{factura.idFactura}" filterMatchMode="contains">
										<h:outputText value="#{factura.numeroFactura}"/>
								    </p:column>
								    
								    <p:column headerText="Fecha" filterBy="#{factura.idFactura}" filterMatchMode="contains">
										<h:outputText value="#{factura.fecha}"/>
								    </p:column>
								    
								    <p:column headerText="IVA">
										<h:outputText value="#{factura.impuesto.porcentaje}"/>
								    </p:column>
								    
								    <p:column headerText="Total bruto">
										<h:outputText value="#{factura.totalBruto}"/>
								    </p:column>
								    
								    <p:column headerText="Total neto">
										<h:outputText value="#{factura.totalNeto}"/>
								    </p:column>
								    
								    <p:column headerText="N° Abonos" filterBy="#{factura.idFactura}" filterMatchMode="contains">
										<h:outputText value="#{factura.cantidadAbonos}"/>
								    </p:column>
								    
								    <p:column headerText="Total Abonos">
										<h:outputText value="#{factura.totalAbonado}"/>
								    </p:column>
								    
								    <p:column headerText="Deuda Actual" filterBy="#{factura.idFactura}" filterMatchMode="contains">
										<h:outputText value="#{factura.deudaActual}"/>
								    </p:column>
								    
								    <p:column exportable="false" style="width:75px" headerText="Modifica">
           								<p:commandButton icon="ui-icon-search" title="Modifica Factura" oncomplete="PF('dialog').show();" update=":form1 :formAuto">
           									<f:setPropertyActionListener value="#{factura}" target="#{facturaBean.facturaSeleccionada}" />
           								</p:commandButton>
       								</p:column>
								    
       								<p:column exportable="false" style="width:70px" headerText="Elimina">
                   						<p:commandButton icon="ui-icon-trash" title="Elimina esta factura" actionListener="#{facturaBean.eliminaFactura(factura)}" update="@form" >
                   							<p:confirm header="Confirma" message="¿ Estás seguro ?" icon="ui-icon-alert" />
                   						</p:commandButton>
       								</p:column>
       								
								</p:dataTable>	
								<!-- END TABLA -->
								<p:confirmDialog global="true" showEffect="fade" hideEffect="fade" closable="false" >
							        <p:commandButton value="Elimina" type="button" styleClass="ui-confirmdialog-yes" icon="ui-icon-check" />
							        <p:commandButton value="Cancela" type="button" styleClass="ui-confirmdialog-no" icon="ui-icon-close" />
							    </p:confirmDialog>
							</div>
						</div>
					</div>
				</div>
			</div>
		</h:form>
		<p:dialog 
			id="idDialog"
			showHeader="false"
			widgetVar="dialog" 
			showEffect="explode"  
			draggable="false" 
			modal="true" 
			closable="false" 
			dynamic="true" 
			position="center"
			resizable="false"
			width="80%"
			height="800px"	>
				
				<div class="row">
					<div class="col-md-12">
						<div class="portlet box grey-cascade">
							<div class="portlet-title">
								<div class="caption">
									<i class="fa fa-globe"></i>Lista de Facturas
								</div>
							</div>
							<div class="portlet-body">
								<div class="table-toolbar">
									<div class="row">
										<div class="col-md-6">
										</div>
										<h:form>
											<h:panelGroup rendered="#{facturaBean.facturaExiste}">
												<div class="col-md-6">
													<div class="btn-group pull-right">
														<button class="btn dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
															Exportar a <i class="fa fa-angle-down"></i>
														</button>
														<ul class="dropdown-menu pull-right">
															<li>
					    										<p:commandButton value="PDF" style="width: 100%; border: 0;" ajax="false" onclick="PrimeFaces.monitorDownload(start, stop);" icon="ui-icon-arrowthick-1-s">
																	<p:fileDownload value="#{facturaBean.content}" />
																</p:commandButton>
															</li>
														</ul>
													</div>
												</div>
											</h:panelGroup>
										</h:form>
									</div>
								</div>
								<div id="sample_1_wrapper" class="dataTables_wrapper no-footer">
									<h:form id="formAuto">
										<div class="row">
											<div class="col-md-6 col-sm-12">
												<div id="sample_1_filter" class="dataTables_filter">
													<h:outputText value="Cliente" />
			        								<p:autoComplete
				        									disabled="#{facturaBean.clientesOcultos}" 
				        									id="clientePojo" 
				        									value="#{facturaBean.clienteSeleccionado}" 
				        									completeMethod="#{facturaBean.buscaClientePorRut}"
				                        					var="cliente" 
				                        					itemLabel="#{cliente.rut}" 
						                        			itemValue="#{cliente}" 
						                        			converter="#{clienteConverter}"
				                        					dropdown="true"
				                        					autocomplete="true">
	
			                        					 <p:ajax event="itemSelect" update=":form1" />
			                        				</p:autoComplete>
												</div>
											</div>
										</div>
		                        	</h:form>
								</div>
								<h:form id="form1" prependId="false">	
									<div>
										<h:outputText value="Factura" />
										<p:inputText value="#{facturaBean.facturaSeleccionada.numeroFactura}"  label="Numero Factura"/>
									</div>
									<p:panel id="tablas">
										<p:growl id="growlTablas" showDetail="true"/>
										
										<div>
											<!-- BEGIN TABLA PRODUCTOS-->
											<p:dataTable 
													id="tablaOrdenes"
													value="#{facturaBean.listadoOrdenesEnFactura}" 
													var="orden"
													paginator="true"
													rows="10"
													rowsPerPageTemplate="10,20,40,60,90,150"
													style="margin-bottom:20px"
													paginatorPosition="bottom"
													emptyMessage="No se encontraron registros">
												
												<f:facet name="header">
													<div align="left">        
														<h:outputText value="Filtrado por :" />
													</div>
												</f:facet>
												
												<p:column headerText="Id">
													<h:outputText value="#{orden.idOrden}"/>
											    </p:column>
												
												<p:column headerText="Fecha">
													<h:outputText value="#{orden.fecha}"/>
											    </p:column>
										    
										    	<p:column headerText="Total bruto">
													<h:outputText value="#{orden.getTotalNeto()}"/>
											    </p:column>
											    
											    <p:column headerText="Total neto">
													<h:outputText value="#{facturaBean.calculaTotalConImpuestoPorOrden(orden)}"/>
											    </p:column>
										    
											    <p:column exportable="false" style="width:70px" headerText="Elimina">
			           								<p:commandButton icon="ui-icon-search" title="Elimina linea" actionListener="#{facturaBean.mueveEliminar(orden)}" update=":form1" />
			       								</p:column>
											</p:dataTable>	
											<!-- END TABLA PRODUCTOS -->
										</div>
										<hr></hr>
										<div>
											<!-- BEGIN TABLA PRODUCTOS-->
											<p:dataTable 
													id="tablaOrdenesFueraDeFactura"
													value="#{facturaBean.listadoOrdenesFueraDeFactura}" 
													var="orden"
													paginator="true"
													rows="10"
													rowsPerPageTemplate="10,20,40,60,90,150"
													style="margin-bottom:20px"
													paginatorPosition="bottom"
													emptyMessage="No se encontraron registros">
												
												<f:facet name="header">
													<div align="left">        
														<h:outputText value="Filtrado por :" />
													</div>
												</f:facet>
												
												<p:column headerText="Id">
													<h:outputText value="#{orden.idOrden}"/>
											    </p:column>
												
												<p:column headerText="Fecha">
													<h:outputText value="#{orden.fecha}"/>
											    </p:column>
											    
											    <p:column headerText="Total neto">
													<h:outputText value="#{orden.getTotalNeto()}"/>
											    </p:column>
											    
											    <p:column headerText="Total + IVA">
													<h:outputText value="#{facturaBean.calculaTotalConImpuestoPorOrden(orden)}"/>
											    </p:column>
											    
										    	<p:column exportable="false" style="width:65px" headerText="Agrega">
			           								<p:commandButton icon="ui-icon-search" title="Agrega linea" actionListener="#{facturaBean.mueveAgregar(orden)}" update=":form1" />
			       								</p:column>
											</p:dataTable>	
											<!-- END TABLA PRODUCTOS -->
										</div>
									</p:panel>
								<hr></hr>
								<div class="form-actions">
									<p:commandButton value="Confirme" id="sample_editable_2_new" class="btn green" actionListener="#{facturaBean.registraFactura()}" />
									<p:button value="Cancela" id="sample_editable_1_edit" class="btn default" oncomplete="PF('dialog').hide()"  />
									<p:panel id="total" style="float: right;">
										<p:panel style="float: right;">
											<label>Total + IVA(#{facturaBean.getFacturaSeleccionada().getImpuesto().getPorcentaje()}%)</label>
											<span>
												<b>
													<h:outputText value="#{facturaBean.calculaTotalConImpuesto()}"/>
												</b>
											</span>
										</p:panel>
										<p:panel style="float: right;">
											<label>Total neto</label>
											<span>
												<b>
													<h:outputText value="#{facturaBean.calculaTotal()}"/>
												</b>
											</span>
										</p:panel>
									</p:panel>
								</div>
			</h:form>	
							</div>
						</div>
					</div>
				</div>
			
		</p:dialog>
	</ui:define>
</ui:composition>
</h:html>